- hosts: docker_hosts
  become: yes
  tasks:
    - name: Update all packages
      yum:
        name: "*"
        state: latest
        update_cache: yes

    - name: Install required packages
      yum:
        name:
          - docker
          - python3-pip
        state: present

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Install Docker Python module (for Ansible docker support)
      pip:
        name: docker
        executable: pip3

    - name: Ensure Docker service is started and enabled
      service:
        name: docker
        state: started
        enabled: true

    - name: Pull Node.js app image from Docker Hub
      docker_image:
        name: soliman14/nodejs-app
        tag: V1
        source: pull

    - name: Stop old container if exists
      docker_container:
        name: nodeapp
        state: stopped
      ignore_errors: yes

    - name: Remove old container if exists
      docker_container:
        name: nodeapp
        state: absent
      ignore_errors: yes

    - name: Run Node.js app container
      docker_container:
        name: nodeapp
        image: soliman14/nodejs-app:V1
        state: started
        restart_policy: always
        published_ports:
          - "80:3000"
