- hosts: docker_hosts
  become: yes
  tasks:
    - name: Setup Docker and deploy Node.js app in one go
      shell: |
        yum update -y && \
        yum install -y docker python3-pip && \
        usermod -aG docker ec2-user && \
        pip3 install docker --ignore-installed && \
        systemctl enable docker && \
        systemctl start docker && \
        docker pull soliman14/nodejs-app:V1 && \
        docker stop nodeapp 2>/dev/null || true && \
        docker rm nodeapp 2>/dev/null || true && \
        docker run -d --name nodeapp --restart always -p 80:3000 soliman14/nodejs-app:V1 && \
        docker ps
