name: CI/CD Pipeline - Tech Autodeploy

on:
  workflow_dispatch:   # 👈 Manual trigger from GitHub Actions UI

jobs:
  # -------------------
  # 1. Terraform Infra
  # -------------------
  terraform:
    name: Terraform Infrastructure
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

  # -------------------
  # 2. Ansible Deploy
  # -------------------
  ansible:
    name: Deploy App with Ansible
    runs-on: ubuntu-latest
    needs: terraform

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Ansible & Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible python3-pip sshpass

      - name: Add Private Key
        run: |
          echo "${{ secrets.ANSIBLE_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Run Ansible Playbook
        run: |
          cd ansible
          ansible-playbook -i ../inventory.ini playbook.yml
