name: CI/CD Pipeline - Tech Autodeploy 22

on:
  workflow_dispatch:

jobs:
  deploy-ansible-destroy:
    name: Deploy, Ansible, Wait, Destroy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform

    steps:
      # Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Terraform setup
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Validate
        run: terraform validate
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Ansible setup
      - name: Install Ansible & Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible python3-pip sshpass

      - name: Add Private Key
        run: |
          echo "${{ secrets.ANSIBLE_PRIVATE_KEY }}" > ansible/private_key.pem
          chmod 600 ansible/private_key.pem

      # Run Ansible Playbook
      - name: Run Ansible Playbook
        working-directory: ./ansible
        run: ansible-playbook -i inventory.ini playbook.yml
